avatar:
  enable: true
  url: https://image2url.com/r2/bucket1/images/1767854498312-5e46c7ed-1d46-48ad-b6e8-26e0f3019b36.jpg
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ˜­
    message: ä¸æƒ³ä¸Šå­¦

menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: ri:cloud-line
    #   count: ä½ çŒœ
  custom:
    title: æ–‡æ¡£
    path: https://yun.yunyoujun.cn
    icon: ri:settings-line


banner:
  enable: true
  title: ç‹å…ˆç”Ÿ
  subtitle: å°‘å¹´å»æ¸¸è¡ï¼Œä¸­å¹´æƒ³æ˜è—
  description: è€æ¥å½“å’Œå°šï¼Œä¸€ç‚·é¦™ä¸­å¿˜æ²§æ¡‘ã€‚
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

mode: auto

search:
  modal: true
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-2.jpg

favicon: https://s1.ax1x.com/2023/03/16/pp8BdB9.jpg

social:
  - name: GitHub
    link: https://github.com/ricardowangyf
    icon: ri:github-line
    color: '#181717'
  - name: E-Mail
    link: mailto:me@wangyufei0909@hotmail.com
    icon: ri:mail-line
    color: '#8E71C1'
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=247102977
    icon: ri:netease-cloud-music-line
    color: '#C10D0C'
  - name: çŸ¥ä¹
    link: https://www.zhihu.com/people/peng-yu-yan-44-15
    icon: ri:zhihu-line
    color: '#0084FF'
  - name: å“”å“©å“”å“©åŠ¨ç”»
    link: https://space.bilibili.com/474868654?spm_id_from=333.1007.0.0
    icon: ri:bilibili-line
    color: '#FF8EB3'

head:
  css:
    fontawesome: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css

girls:
  enable: true

pages:
  - name: äºŒæ¬¡å…ƒ
    url: /girls/
    icon: icon-genderless-line
    color: dodgerblue

tags:
  HTML5/CSS3: crimson
  Hexo: orange
  Javascript: "#21374b"
  Linux: saddlebrown
  Macos: crimson
  Markdown: royalblue
  Vue: dimgray

local_search:
  enable: true

highlight:
  enable: true
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ""

post_meta:
  item_text: false
  created_at: true
  updated_at: true
  categories: true
  tags: true

footer:
  powered: false
  enable: false

wordcloud:
  enable: false

reward:
  enable: false

sidebar:
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-1.jpg
  bg_position: bottom 3rem center
  tagcloud:
    enable: true
    amount: 31

bg_image:
  enable: true
  url: https://s1.ax1x.com/2023/01/28/pSalauD.jpg
  dark: https://s1.ax1x.com/2023/01/28/pSalauD.jpg
  opacity: 0.8

cursor:
  enable: true
  default: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/pointer.cur
  pointer: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/link.cur
  text: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/text.cur

creative_commons:
  license: by-nc-sa
  post: false
  language: deed.zh
  clipboard: false

codeblock:
  copy_btn: true
  prismjs:
    light: default
    dark: tomorrow

cdn:
  css: 
    ionicons: https://cdn.jsdelivr.net/npm/ionicons/dist/css/ionicons.min.css
  js:
    async:
      iconfont: //at.alicdn.com/t/font_1140697_dxory92pb0h.js

github_issues:
  enable: true
  username: Ricardowangyf
  repository: Ricardowangyf.github.io